### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by nvectorrr** [DmitriyyyyS/Update#1]
Please, update your xps9333 repo if u have full-working audio. I have same one, but i can't fix jack3,5.....

**Comment by DmitriyyyyS** [comment]
XPS 9333, I’ll update it, but for jack 3.5, another layout may be required, and if this doesn’t help, then most likely the matter is in the AppleALC kext itself, and more specifically in configuring the nodes and pin-config for this codec.

**Comment by nvectorrr** [comment]
Idk why another layout don't want to work. I tried all mentioned layouts for this codec

**Comment by nvectorrr** [comment]
Sorry, you forgot about me?(

**Comment by DmitriyyyyS** [comment]
I updated EFI, but it doesn’t affect the sound in any way, the reason I said above is not the EFI, but the construction of the AppleALC settings for this codec itself.

**Comment by nvectorrr** [comment]
Thanks for efi, but I got kernel panic if I try to boot with them

**Comment by DmitriyyyyS** [comment]
This means that it causes a panic either in the bootloader or in the kexts, it is better to use the trusted EFI

**Comment by DmitriyyyyS** [comment]
In new versions, there are no improvements for this particular laptop, there is no point in updating as well
